name: GitHub Actions

run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on: [push]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: konvoy-test
          MYSQL_USER: user
          MYSQL_PASSWORD: pass
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3

      - name: Check php version
        run: php -v

      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Composer Validate
        run: composer validate

      - name: Composer Install
        run: composer install

      - name: Run phpunit
        run: vendor/bin/phpunit

      - name: Run phpstan
        run: vendor/bin/phpstan analyse src tests

      - name: Run ecs
        run: vendor/bin/ecs